include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    use_build_context_synchronously: true
    unnecessary_nullable_for_final_variable_declarations: true

dart_code_metrics:
  extends: recommended
  rules:
    - no-empty-block
    - prefer-trailing-comma
  metrics:
    cyclomatic-complexity: 20
    maximum-lines: 200
    maximum-nesting: 5
    number-of-parameters: 4
